
(function(F){"use strict";const {n,p,r,fail,fmt,freq,length,C}=F;const dab={"5A":174.928,"5B":176.640,"5C":178.352,"5D":180.064,"6A":181.936,"6B":183.648,"6C":185.360,"6D":187.072,"7A":188.928,"7B":190.640,"7C":192.352,"7D":194.064,"8A":195.936,"8B":197.648,"8C":199.360,"8D":201.072,"9A":202.928,"9B":204.640,"9C":206.352,"9D":208.064,"10A":209.936,"10B":211.648,"10C":213.360,"10D":215.072,"11A":216.928,"11B":218.640,"11C":220.352,"11D":222.064,"12A":223.936,"12B":225.648,"12C":227.360,"12D":229.072,"13A":230.784,"13B":232.496,"13C":234.208,"13D":235.776,"13E":237.488,"13F":239.200};F.defineMany([
{id:"dtt-channel",category:"Broadcast",title:"UK DTT channel",description:"UHF channel centre and edges.",fields:[{id:"channel",label:"Channel 21–48",value:"32"}],compute:v=>{const q=Math.trunc(n(v.channel));if(!q||q<21||q>48)return fail("Use channel 21–48.");const c=474+(q-21)*8;return r(fmt(c)+" MHz",fmt(c-4)+" to "+fmt(c+4)+" MHz")}},
{id:"dtt-wavelength",category:"Broadcast",title:"DTT wavelength",description:"Wavelength from UK DTT channel.",fields:[{id:"channel",label:"Channel 21–48",value:"32"}],compute:v=>{const q=Math.trunc(n(v.channel));if(!q||q<21||q>48)return fail("Use channel 21–48.");const f=(474+(q-21)*8)*1e6;return r(length(C/f))}},
{id:"dab-block",category:"Broadcast",title:"DAB block",description:"Band III block centre frequency.",fields:[{id:"block",label:"Block",type:"select",options:Object.keys(dab).map(x=>[x,x])}],compute:v=>dab[v.block]?r(fmt(dab[v.block])+" MHz"):fail("Choose a block.")},
{id:"fm-carson",category:"Broadcast",title:"FM occupied bandwidth",description:"Carson’s rule.",fields:[{id:"deviation",label:"Peak deviation (kHz)",value:"75"},{id:"audio",label:"Highest modulating frequency (kHz)",value:"15"}],compute:v=>{const d=p(v.deviation),a=p(v.audio);return !d||!a?fail("Enter positive values."):r(fmt(2*(d+a))+" kHz")}},
{id:"fm-mod-index",category:"Broadcast",title:"FM modulation index",description:"Peak deviation divided by modulating frequency.",fields:[{id:"deviation",label:"Peak deviation (kHz)",value:"75"},{id:"audio",label:"Modulating frequency (kHz)",value:"15"}],compute:v=>{const d=p(v.deviation),a=p(v.audio);return !d||!a?fail("Enter positive values."):r(fmt(d/a))}},
{id:"satellite-if",category:"Broadcast",title:"Satellite RF / IF",description:"Low-side or high-side mixer output.",fields:[{id:"mode",label:"Injection",type:"select",options:[["low","Low-side LO"],["high","High-side LO"]]},{id:"rf",label:"RF (MHz)",value:"12000"},{id:"lo",label:"LO (MHz)",value:"9750"}],compute:v=>{const a=p(v.rf),b=p(v.lo);if(!a||!b)return fail("Enter positive values.");const x=v.mode==="low"?a-b:b-a;return x<0?fail("Selected LO produces a negative IF."):r(fmt(x)+" MHz")}},
{id:"dish-gain",category:"Broadcast",title:"Dish antenna gain",description:"Parabolic dish gain from diameter and efficiency.",fields:[{id:"diameter",label:"Diameter (m)",value:"1.2"},{id:"frequency",label:"Frequency (GHz)",value:"12"},{id:"eff",label:"Efficiency (%)",value:"60"}],compute:v=>{const D=p(v.diameter),f=p(v.frequency),e=p(v.eff);if(!D||!f||!e)return fail("Enter positive values.");const l=C/(f*1e9),g=e/100*(Math.PI*D/l)**2;return r(fmt(10*Math.log10(g))+" dBi")}},
{id:"dish-beamwidth",category:"Broadcast",title:"Dish beamwidth",description:"Approximate half-power beamwidth.",fields:[{id:"diameter",label:"Diameter (m)",value:"1.2"},{id:"frequency",label:"Frequency (GHz)",value:"12"}],compute:v=>{const D=p(v.diameter),f=p(v.frequency);return !D||!f?fail("Enter positive values."):r(fmt(70*(C/(f*1e9))/D)+"°")}},
{id:"symbol-bitrate",category:"Broadcast",title:"Symbol rate to bitrate",description:"Gross bit rate from modulation order and coding rate.",fields:[{id:"symbols",label:"Symbol rate (Msym/s)",value:"6.9"},{id:"bits",label:"Bits per symbol",value:"2"},{id:"code",label:"Code rate",value:"0.75"}],compute:v=>{const s=p(v.symbols),b=p(v.bits),c=p(v.code);return !s||!b||!c||c>1?fail("Code rate must be 0–1."):r(fmt(s*b*c)+" Mbit/s")}},
{id:"dvbs-bandwidth",category:"Broadcast",title:"DVB-S/S2 occupied bandwidth",description:"Symbol rate and roll-off estimate.",fields:[{id:"symbols",label:"Symbol rate (Msym/s)",value:"27.5"},{id:"rolloff",label:"Roll-off",value:"0.35"}],compute:v=>{const s=p(v.symbols),a=n(v.rolloff);return !s||a===null||a<0?fail("Enter valid values."):r(fmt(s*(1+a))+" MHz")}},
{id:"mer-evm",category:"Broadcast",title:"MER ↔ EVM",description:"Convert modulation error ratio and RMS EVM.",fields:[{id:"mode",label:"Direction",type:"select",options:[["mer","MER to EVM"],["evm","EVM to MER"]]},{id:"value",label:"Value",value:"30"}],compute:v=>{const x=p(v.value);if(!x)return fail("Enter a positive value.");return v.mode==="mer"?r(fmt(100*10**(-x/20))+"% EVM"):r(fmt(-20*Math.log10(x/100))+" dB MER")}},
{id:"cn-ebn0",category:"Broadcast",title:"C/N ↔ Eb/N0",description:"Convert carrier-to-noise and bit-energy ratio.",fields:[{id:"mode",label:"Direction",type:"select",options:[["cn","C/N to Eb/N0"],["eb","Eb/N0 to C/N"]]},{id:"value",label:"Level (dB)",value:"12"},{id:"bandwidth",label:"Noise bandwidth (MHz)",value:"8"},{id:"bitrate",label:"Bit rate (Mbit/s)",value:"20"}],compute:v=>{const x=n(v.value),B=p(v.bandwidth),R=p(v.bitrate);if(x===null||!B||!R)return fail("Enter all values.");const d=10*Math.log10(B/R);return v.mode==="cn"?r(fmt(x+d)+" dB Eb/N0"):r(fmt(x-d)+" dB C/N")}},
{id:"transport-storage",category:"Broadcast",title:"Transport-stream storage",description:"Storage required for a constant bit rate.",fields:[{id:"bitrate",label:"Bit rate (Mbit/s)",value:"20"},{id:"hours",label:"Duration (h)",value:"1"}],compute:v=>{const b=p(v.bitrate),h=p(v.hours);return !b||!h?fail("Enter positive values."):r(fmt(b*1e6*h*3600/8/1e9)+" GB")}}
]);})(FOCalc);
