
(function(F){"use strict";const {n,p,r,fail,fmt,length,C}=F;F.defineMany([
{id:"cable-loss",category:"Cable",title:"Cable loss",description:"Total cable loss from length and loss per 100 m.",fields:[{id:"length",label:"Length (m)",value:"50"},{id:"rate",label:"Loss (dB/100 m)",value:"6.6"}],compute:v=>{const L=p(v.length),q=n(v.rate);return !L||q===null?fail("Enter valid values."):r(fmt(L/100*q)+" dB")}},
{id:"cable-system-loss",category:"Cable",title:"Cable system loss",description:"Cable plus connectors, pads and splitters.",fields:[{id:"cable",label:"Cable loss (dB)",value:"3.3"},{id:"connectors",label:"Connector count",value:"2"},{id:"perConnector",label:"Loss per connector (dB)",value:"0.1"},{id:"other",label:"Other losses (dB)",value:"0"}],compute:v=>{const a=n(v.cable),b=n(v.connectors),c=n(v.perConnector),d=n(v.other);return [a,b,c,d].some(x=>x===null)?fail("Enter all values."):r(fmt(a+b*c+d)+" dB")}},
{id:"cable-delay",category:"Cable",title:"Cable propagation delay",description:"Delay from length and velocity factor.",fields:[{id:"length",label:"Length (m)",value:"100"},{id:"vf",label:"Velocity factor",value:"0.85"}],compute:v=>{const L=p(v.length),q=p(v.vf);return !L||!q||q>1?fail("VF must be 0–1."):r(fmt(L/(C*q)*1e9)+" ns")}},
{id:"cable-electrical-length",category:"Cable",title:"Cable electrical length",description:"Electrical phase length at a frequency.",fields:[{id:"length",label:"Physical length (m)",value:"1"},{id:"vf",label:"Velocity factor",value:"0.85"},{id:"frequency",label:"Frequency (MHz)",value:"100"}],compute:v=>{const L=p(v.length),q=p(v.vf),f=p(v.frequency);if(!L||!q||!f||q>1)return fail("Enter valid values.");return r(fmt(L/(C*q/(f*1e6))*360)+"°")}},
{id:"quarter-wave-cable",category:"Cable",title:"Quarter-wave cable",description:"Physical length for a quarter-wave section.",fields:[{id:"frequency",label:"Frequency (MHz)",value:"100"},{id:"vf",label:"Velocity factor",value:"0.85"}],compute:v=>{const f=p(v.frequency),q=p(v.vf);return !f||!q||q>1?fail("Enter valid values."):r(length(C/(f*1e6)*q/4))}},
{id:"coax-impedance",category:"Cable",title:"Coax characteristic impedance",description:"Approximate impedance from diameters and dielectric constant.",fields:[{id:"outer",label:"Shield inner diameter (mm)",value:"7.25"},{id:"inner",label:"Conductor diameter (mm)",value:"1.63"},{id:"er",label:"Relative permittivity",value:"2.25"}],compute:v=>{const D=p(v.outer),d=p(v.inner),e=p(v.er);return !D||!d||!e||D<=d?fail("Outer diameter must exceed inner."):r(fmt(60/Math.sqrt(e)*Math.log(D/d))+" Ω")}},
{id:"fibre-budget",category:"Cable",title:"Fibre loss budget",description:"Link loss and remaining optical margin.",fields:[{id:"length",label:"Length (km)",value:"10"},{id:"atten",label:"Fibre loss (dB/km)",value:"0.35"},{id:"connectors",label:"Connector count",value:"2"},{id:"connectorLoss",label:"Connector loss (dB)",value:"0.5"},{id:"splices",label:"Splice count",value:"4"},{id:"spliceLoss",label:"Splice loss (dB)",value:"0.1"},{id:"budget",label:"Available budget (dB)",value:"15"}],compute:v=>{const xs=["length","atten","connectors","connectorLoss","splices","spliceLoss","budget"].map(k=>n(v[k]));if(xs.some(x=>x===null))return fail("Enter all values.");const loss=xs[0]*xs[1]+xs[2]*xs[3]+xs[4]*xs[5];return r(fmt(loss)+" dB loss",fmt(xs[6]-loss)+" dB margin")}}
]);})(FOCalc);
