
(function(F){"use strict";const {n,p,r,fail,fmt}=F;F.defineMany([
{id:"percentage-change",category:"General",title:"Percentage change",description:"Change from an original value to a new value.",fields:[{id:"old",label:"Original",value:"100"},{id:"new",label:"New",value:"125"}],compute:v=>{const a=n(v.old),b=n(v.new);return a===null||b===null||a===0?fail("Original must be non-zero."):r(fmt((b-a)/a*100)+"%",fmt(b-a)+" absolute change")}},
{id:"percentage-difference",category:"General",title:"Percentage difference",description:"Symmetrical percentage difference between two values.",fields:[{id:"a",label:"Value A",value:"100"},{id:"b",label:"Value B",value:"110"}],compute:v=>{const a=n(v.a),b=n(v.b),m=(Math.abs(a)+Math.abs(b))/2;return a===null||b===null||m===0?fail("Enter two usable values."):r(fmt(Math.abs(a-b)/m*100)+"%")}},
{id:"reverse-percentage",category:"General",title:"Reverse percentage",description:"Recover the original value before a percentage change.",fields:[{id:"final",label:"Final value",value:"120"},{id:"percent",label:"Change (%)",value:"20"}],compute:v=>{const f=n(v.final),q=n(v.percent);return f===null||q===null||1+q/100===0?fail("Invalid values."):r(fmt(f/(1+q/100)),"Original value")}},
{id:"ratio-proportion",category:"General",title:"Ratio and proportion",description:"Solve a:b = c:x.",fields:[{id:"a",label:"A",value:"2"},{id:"b",label:"B",value:"3"},{id:"c",label:"C",value:"10"}],compute:v=>{const a=n(v.a),b=n(v.b),c=n(v.c);return a===null||b===null||c===null||a===0?fail("A must be non-zero."):r(fmt(b*c/a),"X")}},
{id:"arithmetic-mean",category:"General",title:"Average",description:"Mean, minimum and maximum of a list.",fields:[{id:"values",label:"Values (comma separated)",type:"text",value:"10,12,15,18"}],compute:v=>{const xs=String(v.values).split(/[ ,;]+/).filter(Boolean).map(Number);return !xs.length||xs.some(x=>!Number.isFinite(x))?fail("Enter numeric values."):r(fmt(xs.reduce((a,b)=>a+b,0)/xs.length),"Min "+fmt(Math.min(...xs))+" · Max "+fmt(Math.max(...xs))+" · n="+xs.length)}},
{id:"weighted-average",category:"General",title:"Weighted average",description:"Weighted mean from values and weights.",fields:[{id:"values",label:"Values",type:"text",value:"10,20,30"},{id:"weights",label:"Weights",type:"text",value:"1,2,1"}],compute:v=>{const xs=String(v.values).split(/[ ,;]+/).filter(Boolean).map(Number),ws=String(v.weights).split(/[ ,;]+/).filter(Boolean).map(Number);if(xs.length!==ws.length||!xs.length||xs.some(x=>!Number.isFinite(x))||ws.some(x=>!Number.isFinite(x)))return fail("Use equal-length numeric lists.");const sw=ws.reduce((a,b)=>a+b,0);return sw===0?fail("Weight sum must be non-zero."):r(fmt(xs.reduce((s,x,i)=>s+x*ws[i],0)/sw))}},
{id:"standard-deviation",category:"General",title:"Standard deviation",description:"Population and sample standard deviation.",fields:[{id:"values",label:"Values",type:"text",value:"10,12,15,18"}],compute:v=>{const xs=String(v.values).split(/[ ,;]+/).filter(Boolean).map(Number);if(xs.some(x=>!Number.isFinite(x)))return fail("Enter numeric values only.");if(xs.length<2)return fail("Enter at least two values.");const m=xs.reduce((a,b)=>a+b,0)/xs.length,ss=xs.reduce((s,x)=>s+(x-m)**2,0);return r("Population "+fmt(Math.sqrt(ss/xs.length)),"Sample "+fmt(Math.sqrt(ss/(xs.length-1))))}},
{id:"linear-interpolation",category:"General",title:"Linear interpolation",description:"Interpolate y at x between two points.",fields:[{id:"x1",label:"x1",value:"0"},{id:"y1",label:"y1",value:"0"},{id:"x2",label:"x2",value:"10"},{id:"y2",label:"y2",value:"100"},{id:"x",label:"x",value:"4"}],compute:v=>{const x1=n(v.x1),y1=n(v.y1),x2=n(v.x2),y2=n(v.y2),x=n(v.x);return [x1,y1,x2,y2,x].some(q=>q===null)||x2===x1?fail("Enter valid distinct x points."):r(fmt(y1+(x-x1)*(y2-y1)/(x2-x1)))}},
{id:"significant-figures",category:"General",title:"Significant figures",description:"Round a value to a selected number of significant figures.",fields:[{id:"value",label:"Value",value:"12345.678"},{id:"digits",label:"Significant figures",value:"4"}],compute:v=>{const x=n(v.value),d=Math.trunc(n(v.digits));return x===null||!d||d<1||d>15?fail("Digits must be 1–15."):r(Number(x.toPrecision(d)).toString())}},
{id:"pythagoras",category:"General",title:"Pythagoras",description:"Hypotenuse from two perpendicular sides.",fields:[{id:"a",label:"Side A",value:"3"},{id:"b",label:"Side B",value:"4"}],compute:v=>{const a=p(v.a),b=p(v.b);return !a||!b?fail("Sides must be positive."):r(fmt(Math.hypot(a,b)))}},
{id:"right-triangle",category:"General",title:"Right triangle solver",description:"Solve hypotenuse and angles from two legs.",fields:[{id:"a",label:"Opposite",value:"3"},{id:"b",label:"Adjacent",value:"4"}],compute:v=>{const a=p(v.a),b=p(v.b);if(!a||!b)return fail("Sides must be positive.");const c=Math.hypot(a,b),A=Math.atan2(a,b)*180/Math.PI;return r("Hypotenuse "+fmt(c),"Angles "+fmt(A)+"° / "+fmt(90-A)+"°")}},
{id:"circle",category:"General",title:"Circle",description:"Area and circumference from radius.",fields:[{id:"radius",label:"Radius",value:"1"}],compute:v=>{const x=p(v.radius);return !x?fail("Radius must be positive."):r("Area "+fmt(Math.PI*x*x),"Circumference "+fmt(2*Math.PI*x))}},
{id:"cylinder",category:"General",title:"Cylinder volume",description:"Volume and surface area.",fields:[{id:"radius",label:"Radius",value:"1"},{id:"height",label:"Height",value:"2"}],compute:v=>{const a=p(v.radius),h=p(v.height);return !a||!h?fail("Enter positive radius and height."):r("Volume "+fmt(Math.PI*a*a*h),"Surface area "+fmt(2*Math.PI*a*(a+h)))}},
{id:"speed-distance-time",category:"General",title:"Speed, distance and time",description:"Calculate distance from speed and time.",fields:[{id:"speed",label:"Speed",value:"60"},{id:"time",label:"Time",value:"2"}],compute:v=>{const s=n(v.speed),t=n(v.time);return s===null||t===null?fail("Enter both values."):r(fmt(s*t),"Distance in matching units")}},
{id:"density-mass-volume",category:"General",title:"Density, mass and volume",description:"Calculate density from mass and volume.",fields:[{id:"mass",label:"Mass",value:"1000"},{id:"volume",label:"Volume",value:"1"}],compute:v=>{const m=n(v.mass),vol=p(v.volume);return m===null||!vol?fail("Volume must be positive."):r(fmt(m/vol),"Density")}},
{id:"journey-cost",category:"General",title:"Journey fuel cost",description:"Distance, consumption and fuel price.",fields:[{id:"distance",label:"Distance (miles)",value:"100"},{id:"mpg",label:"Economy (UK mpg)",value:"40"},{id:"price",label:"Fuel price (£/L)",value:"1.45"}],compute:v=>{const d=p(v.distance),mpg=p(v.mpg),price=p(v.price);if(!d||!mpg||!price)return fail("Enter positive values.");const litres=d/mpg*4.54609;return r("£"+fmt(litres*price),fmt(litres)+" L")}}
]);})(FOCalc);
