
(function(F){"use strict";const {n,p,r,fail,fmt,freq}=F;F.defineMany([
{id:"scope-bandwidth",category:"Instruments",title:"Scope bandwidth from rise time",description:"Bandwidth estimate for a measured edge.",fields:[{id:"rise",label:"Rise time (ns)",value:"5"},{id:"factor",label:"Factor",type:"select",options:[["0.35","0.35 Gaussian"],["0.45","0.45 margin"]]}],compute:v=>{const t=p(v.rise),q=p(v.factor);return !t||!q?fail("Enter positive values."):r(freq(q/(t*1e-9)))}},
{id:"scope-rise-time",category:"Instruments",title:"Rise time from bandwidth",description:"Theoretical instrument rise time.",fields:[{id:"bandwidth",label:"Bandwidth (MHz)",value:"100"},{id:"factor",label:"Factor",type:"select",options:[["0.35","0.35 Gaussian"],["0.45","0.45 margin"]]}],compute:v=>{const b=p(v.bandwidth),q=p(v.factor);return !b||!q?fail("Enter positive values."):r(fmt(q/(b*1e6)*1e9)+" ns")}},
{id:"sample-rate",category:"Instruments",title:"Minimum sample rate",description:"Sample rate from bandwidth and samples per cycle.",fields:[{id:"bandwidth",label:"Bandwidth (MHz)",value:"100"},{id:"samples",label:"Samples per cycle",value:"10"}],compute:v=>{const b=p(v.bandwidth),s=p(v.samples);return !b||!s?fail("Enter positive values."):r(fmt(b*s)+" MS/s")}},
{id:"record-length",category:"Instruments",title:"Oscilloscope record length",description:"Required samples for time span and sample rate.",fields:[{id:"time",label:"Time span (ms)",value:"10"},{id:"rate",label:"Sample rate (MS/s)",value:"100"}],compute:v=>{const t=p(v.time),q=p(v.rate);return !t||!q?fail("Enter positive values."):r(fmt(t*1e-3*q*1e6)+" samples")}},
{id:"fft-bin",category:"Instruments",title:"FFT bin width",description:"Frequency resolution from sample rate and FFT length.",fields:[{id:"rate",label:"Sample rate (MS/s)",value:"100"},{id:"points",label:"FFT points",value:"65536"}],compute:v=>{const q=p(v.rate),N=p(v.points);return !q||!N?fail("Enter positive values."):r(freq(q*1e6/N))}},
{id:"rbw-correction",category:"Instruments",title:"RBW noise correction",description:"Adjust noise level between bandwidths.",fields:[{id:"level",label:"Measured noise (dBm)",value:"-90"},{id:"rbw1",label:"Original RBW (Hz)",value:"10000"},{id:"rbw2",label:"New RBW (Hz)",value:"1000"}],compute:v=>{const x=n(v.level),a=p(v.rbw1),b=p(v.rbw2);return x===null||!a||!b?fail("Enter all values."):r(fmt(x+10*Math.log10(b/a))+" dBm")}},
{id:"generator-correction",category:"Instruments",title:"Generator level correction",description:"Correct set level for cable and pad loss.",fields:[{id:"wanted",label:"Wanted DUT level (dBm)",value:"-10"},{id:"cable",label:"Cable loss (dB)",value:"2"},{id:"pad",label:"Pad/fixture loss (dB)",value:"10"}],compute:v=>{const a=n(v.wanted),b=n(v.cable),c=n(v.pad);return [a,b,c].some(x=>x===null)?fail("Enter all values."):r(fmt(a+b+c)+" dBm generator setting")}},
{id:"dmm-loading",category:"Instruments",title:"DMM loading error",description:"Voltage error from source resistance and meter input.",fields:[{id:"source",label:"Source resistance (Ω)",value:"1000000"},{id:"meter",label:"Meter input (MΩ)",value:"10"},{id:"voltage",label:"Open-circuit voltage (V)",value:"10"}],compute:v=>{const s=p(v.source),m=p(v.meter),V=n(v.voltage);if(!s||!m||V===null)return fail("Enter valid values.");const ratio=(m*1e6)/(s+m*1e6),measured=V*ratio;return r(fmt(measured)+" V",fmt((1-ratio)*100)+"% low")}},
{id:"probe-loading",category:"Instruments",title:"Scope probe capacitive loading",description:"Probe reactance at frequency.",fields:[{id:"frequency",label:"Frequency (MHz)",value:"10"},{id:"capacitance",label:"Probe capacitance (pF)",value:"10"}],compute:v=>{const f=p(v.frequency),C=p(v.capacitance);return !f||!C?fail("Enter positive values."):r(fmt(1/(2*Math.PI*f*1e6*C*1e-12))+" Ω XC")}},
{id:"uncertainty-rss",category:"Instruments",title:"Uncertainty RSS",description:"Combine independent uncertainty terms.",fields:[{id:"values",label:"Uncertainties",type:"text",value:"0.5,0.2,0.1"}],compute:v=>{const xs=String(v.values).split(/[ ,;]+/).filter(Boolean).map(Number);return !xs.length||xs.some(x=>!Number.isFinite(x))?fail("Enter numeric values."):r(fmt(Math.sqrt(xs.reduce((s,x)=>s+x*x,0))))}}
]);})(FOCalc);
