
(function(F){"use strict";const {n,p,r,fail,fmt}=F;F.defineMany([
{id:"loop-4-20",category:"Sensors",title:"4–20 mA scaling",description:"Convert loop current to engineering units.",fields:[{id:"current",label:"Current (mA)",value:"12"},{id:"low",label:"Low engineering value",value:"0"},{id:"high",label:"High engineering value",value:"100"}],compute:v=>{const I=n(v.current),a=n(v.low),b=n(v.high);return [I,a,b].some(x=>x===null)?fail("Enter all values."):r(fmt(a+(I-4)/16*(b-a))) }},
{id:"loop-4-20-reverse",category:"Sensors",title:"Engineering units to 4–20 mA",description:"Calculate required loop current.",fields:[{id:"value",label:"Engineering value",value:"50"},{id:"low",label:"Low value",value:"0"},{id:"high",label:"High value",value:"100"}],compute:v=>{const x=n(v.value),a=n(v.low),b=n(v.high);return [x,a,b].some(q=>q===null)||b===a?fail("Enter a valid span."):r(fmt(4+16*(x-a)/(b-a))+" mA")}},
{id:"voltage-scaling",category:"Sensors",title:"0–10 V scaling",description:"Convert voltage to engineering units.",fields:[{id:"voltage",label:"Voltage (V)",value:"5"},{id:"low",label:"Low value",value:"0"},{id:"high",label:"High value",value:"100"}],compute:v=>{const x=n(v.voltage),a=n(v.low),b=n(v.high);return [x,a,b].some(q=>q===null)?fail("Enter all values."):r(fmt(a+x/10*(b-a))) }},
{id:"pt100",category:"Sensors",title:"PT100 temperature",description:"Approximate IEC 60751 temperature above 0 °C.",fields:[{id:"resistance",label:"Resistance (Ω)",value:"119.4"}],compute:v=>{const R=p(v.resistance);return !R?fail("Enter positive resistance."):r(fmt((R/100-1)/0.00385)+" °C","Linear approximation")}},
{id:"pt1000",category:"Sensors",title:"PT1000 temperature",description:"Approximate IEC 60751 temperature above 0 °C.",fields:[{id:"resistance",label:"Resistance (Ω)",value:"1194"}],compute:v=>{const R=p(v.resistance);return !R?fail("Enter positive resistance."):r(fmt((R/1000-1)/0.00385)+" °C","Linear approximation")}},
{id:"thermistor-beta",category:"Sensors",title:"NTC thermistor beta",description:"Temperature from resistance and beta coefficient.",fields:[{id:"resistance",label:"Measured resistance (Ω)",value:"5000"},{id:"r0",label:"R0 at T0 (Ω)",value:"10000"},{id:"t0",label:"T0 (°C)",value:"25"},{id:"beta",label:"Beta (K)",value:"3950"}],compute:v=>{const R=p(v.resistance),R0=p(v.r0),T0=n(v.t0),B=p(v.beta);if(!R||!R0||T0===null||!B)return fail("Enter valid values.");const K=1/(1/(T0+273.15)+Math.log(R/R0)/B);return r(fmt(K-273.15)+" °C")}},
{id:"two-point-calibration",category:"Sensors",title:"Two-point calibration",description:"Slope, intercept and corrected output.",fields:[{id:"x1",label:"Input 1",value:"4"},{id:"y1",label:"Output 1",value:"0"},{id:"x2",label:"Input 2",value:"20"},{id:"y2",label:"Output 2",value:"100"},{id:"x",label:"Measured input",value:"12"}],compute:v=>{const xs=["x1","y1","x2","y2","x"].map(k=>n(v[k]));if(xs.some(q=>q===null)||xs[2]===xs[0])return fail("Use distinct calibration inputs.");const m=(xs[3]-xs[1])/(xs[2]-xs[0]),b=xs[1]-m*xs[0];return r(fmt(m*xs[4]+b),"Slope "+fmt(m)+" · Offset "+fmt(b))}}
]);})(FOCalc);
