/* ==========================================================================
   FieldOps Atlas - UK electricity outages
   File: FieldOpsAtlas/Features/Weather/outages.js
   Version: 0.4.3-postcode-points

   The browser loads same-origin GeoJSON files generated by the repository
   outage collector. External provider APIs never touch the Leaflet map.
   ========================================================================== */

(() => {
  "use strict";

  const VERSION = "0.4.3-postcode-points";
  const ACTIVE_SOURCES_KEY = "fieldops-outage-active-sources-v2";
  const VISIBLE_REGIONS_KEY = "fieldops-outage-visible-regions-v1";
  const SELECTOR_COMPLETE_KEY = "fieldops-outage-selector-complete-v2";
  const MAP_VIEW_KEY = "fieldops-weather-map-view-v1";
  const REFRESH_MS = 5 * 60 * 1000;
  const DATA_ROOT = "data/outages";
  const UK_BOUNDS = [[49.5, -11.0], [61.2, 2.7]];
  const OSM_TILE_URL = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
  const OSM_ATTRIBUTION =
    '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>';

  const PROVIDERS = [
    {
      id: "ukpn",
      name: "UK Power Networks",
      officialUrl: "https://www.ukpowernetworks.co.uk/power-cut/map"
    },
    {
      id: "npg",
      name: "Northern Powergrid",
      officialUrl: "https://www.northernpowergrid.com/power-cuts-map"
    },
    {
      id: "nged",
      name: "National Grid ED",
      officialUrl: "https://powercuts.nationalgrid.co.uk/power-cut-map"
    },
    {
      id: "enwl",
      name: "Electricity North West",
      officialUrl: "https://www.enwl.co.uk/power-cuts"
    },
    {
      id: "ssen",
      name: "SSEN Distribution",
      officialUrl: "https://powertrack.ssen.co.uk/powertrack"
    },
    {
      id: "spen",
      name: "SP Energy Networks",
      officialUrl: "https://powercuts.spenergynetworks.co.uk/map"
    },
    {
      id: "nie",
      name: "NIE Networks",
      officialUrl: "https://powercheck.nienetworks.co.uk/"
    }
  ];

  const OUTAGE_REGIONS = [
    { id: "scotland", label: "Scotland", bounds: [[55.0, -8.7], [61.1, -0.7]], x: 48, y: 16, colour: "#3fa9f5" },
    { id: "north", label: "North", bounds: [[53.0, -4.2], [55.25, -0.7]], x: 65, y: 34, colour: "#3fa9f5" },
    { id: "midlands", label: "Midlands", bounds: [[51.75, -3.45], [53.35, -0.5]], x: 70, y: 50, colour: "#3fa9f5" },
    { id: "london", label: "London", bounds: [[51.05, -0.7], [51.9, 0.45]], x: 79, y: 64, colour: "#3fa9f5" },
    { id: "south-east", label: "South East", bounds: [[50.65, -1.25], [51.75, 1.75]], x: 76, y: 82, colour: "#3fa9f5" },
    { id: "south-west", label: "South West", bounds: [[49.85, -6.35], [51.75, -1.75]], x: 30, y: 87, colour: "#3fa9f5" },
    { id: "wales-west", label: "Wales & West", bounds: [[51.3, -5.75], [53.65, -2.2]], x: 16, y: 64, colour: "#58dd72", featured: true }
  ];

  const state = {
    map: null,
    providerLayers: new Map(),
    providerRecords: new Map(),
    providerStatus: new Map(),
    regionLayers: new Map(),
    firstSeen: new Map(),
    activeSources: new Set(),
    visibleRegions: new Set(),
    pendingRegions: new Set(),
    selectorComplete: false,
    refreshSequence: 0,
    refreshTimer: null,
    renderTimer: null,
    collectorGeneratedAt: null
  };

  const elements = {};

  function init() {
    captureElements();
    state.activeSources = readActiveSources();
    state.visibleRegions = readVisibleRegions();
    state.pendingRegions = new Set(state.visibleRegions);
    state.selectorComplete = readSelectorComplete();
    initPanels();

    if (!window.L || !elements.map) {
      setHeadline("Map unavailable", "error");
      return;
    }

    initMap();
    bindControls();
    renderSourceList();
    refreshAll();

    state.refreshTimer = window.setInterval(refreshAll, REFRESH_MS);
    state.renderTimer = window.setInterval(refreshAnimatedMarkers, 1000);
  }

  function captureElements() {
    elements.map = document.getElementById("outageMap");
    elements.sourceSummary = document.getElementById("sourceSummary");
    elements.sourceList = document.getElementById("sourceList");
    elements.activateAllProviders = document.getElementById("activateAllProviders");
    elements.deactivateAllProviders = document.getElementById("deactivateAllProviders");
    elements.regionSummary = document.getElementById("regionSummary");
    elements.regionList = document.getElementById("regionList");
    elements.regionOk = document.getElementById("regionOk");
    elements.regionReset = document.getElementById("regionReset");
    elements.selectorOverlay = document.getElementById("outageRegionSelector");
    elements.headlineStatus = document.getElementById("headlineStatus");
    elements.liveBadge = document.getElementById("liveBadge");
    elements.statusText = document.getElementById("statusText");
    elements.showCurrent = document.getElementById("showCurrent");
    elements.showPlanned = document.getElementById("showPlanned");
    elements.showRestored = document.getElementById("showRestored");
    elements.refresh = document.getElementById("refreshOutages");
    elements.ukView = document.getElementById("ukView");
    elements.changeRegions = document.getElementById("changeRegions");
    elements.currentCount = document.getElementById("currentCount");
    elements.plannedCount = document.getElementById("plannedCount");
    elements.restoredCount = document.getElementById("restoredCount");
    elements.providerCount = document.getElementById("providerCount");
    elements.rawRowCount = document.getElementById("rawRowCount");
    elements.uniqueIncidentCount = document.getElementById("uniqueIncidentCount");
    elements.groupedRowCount = document.getElementById("groupedRowCount");
    elements.animationDuration = document.getElementById("newIncidentAnimation");
  }

  function initPanels() {
    document.querySelectorAll(".outage-panel").forEach((panel) => {
      panel.addEventListener("toggle", () => {
        window.setTimeout(() => state.map?.invalidateSize({ pan: false }), 120);
      });
    });
  }

  function initMap() {
    const storedView = readMapView();
    state.map = window.L.map(elements.map, {
      center: storedView?.center || [54.7, -3.2],
      zoom: storedView?.zoom || 5,
      minZoom: 3,
      maxZoom: 14,
      zoomControl: false,
      attributionControl: true,
      preferCanvas: true,
      worldCopyJump: false
    });

    const basePane = state.map.createPane("outageBasePane");
    basePane.style.zIndex = "190";
    basePane.classList.add("weather-base-pane");

    const markerPane = state.map.createPane("outageMarkerPane");
    markerPane.style.zIndex = "620";
    markerPane.classList.add("weather-marker-pane");

    const regionPane = state.map.createPane("outageRegionPane");
    regionPane.style.zIndex = "360";
    regionPane.classList.add("outage-region-pane");

    window.L.control.zoom({ position: "topright" }).addTo(state.map);

    window.L.tileLayer(OSM_TILE_URL, {
      pane: "outageBasePane",
      minZoom: 3,
      maxZoom: 14,
      noWrap: true,
      keepBuffer: 1,
      updateWhenIdle: true,
      updateWhenZooming: false,
      attribution: OSM_ATTRIBUTION
    }).addTo(state.map);

    initialiseProviderLayers();
    initialiseRegionLayers();
    exposeWeatherMapHooks();
    state.map.on("moveend zoomend", () => rememberMapView());
    syncProviderVisibility();
    syncMarkerVisibility();
    syncRegionHighlights();
    if (!storedView) fitUkView();
    window.setTimeout(() => state.map.invalidateSize(), 160);
  }

  function exposeWeatherMapHooks() {
    window.FieldOpsWeatherMap = {
      remember: rememberMapView,
      invalidate: () => window.setTimeout(() => state.map?.invalidateSize({ pan: false }), 80)
    };
    window.addEventListener("fieldops:weather-shell-resize", window.FieldOpsWeatherMap.invalidate);
  }

  function readMapView() {
    try {
      const parsed = JSON.parse(window.sessionStorage.getItem(MAP_VIEW_KEY) || "null");
      if (
        Array.isArray(parsed?.center) &&
        parsed.center.length === 2 &&
        parsed.center.every(Number.isFinite) &&
        Number.isFinite(parsed.zoom)
      ) {
        return parsed;
      }
    } catch {
      // Default map view remains available.
    }

    return null;
  }

  function rememberMapView() {
    if (!state.map?.getCenter) return;

    try {
      const center = state.map.getCenter();
      window.sessionStorage.setItem(MAP_VIEW_KEY, JSON.stringify({
        center: [center.lat, center.lng],
        zoom: state.map.getZoom()
      }));
    } catch {
      // Session storage is optional.
    }
  }

  function initialiseProviderLayers() {
    PROVIDERS.forEach((provider) => {
      const root = window.L.layerGroup();
      const current = window.L.layerGroup();
      const planned = window.L.layerGroup();
      const restored = window.L.layerGroup();

      root.addLayer(current);
      root.addLayer(planned);
      root.addLayer(restored);

      state.providerLayers.set(provider.id, {
        root,
        current,
        planned,
        restored
      });

      state.providerRecords.set(provider.id, []);
      state.providerStatus.set(provider.id, {
        state: "waiting",
        message: "Waiting for collected data",
        rawRows: 0,
        groupedRows: 0,
        uniqueIncidents: 0,
        stale: false,
        loaded: false
      });
    });
  }

  function bindControls() {
    elements.refresh?.addEventListener("click", refreshAll);
    elements.ukView?.addEventListener("click", fitUkView);

    [elements.showCurrent, elements.showPlanned, elements.showRestored]
      .forEach((input) => input?.addEventListener("change", () => {
        syncMarkerVisibility();
        updateSummary();
      }));

    elements.animationDuration?.addEventListener("change", refreshAnimatedMarkers);

    elements.sourceList?.addEventListener("click", (event) => {
      const button = event.target.closest("[data-source-toggle]");
      if (!button) return;

      const sourceId = button.getAttribute("data-source-toggle");
      setSourceActive(sourceId, !state.activeSources.has(sourceId));
    });

    elements.activateAllProviders?.addEventListener("click", () => {
      state.activeSources = new Set(PROVIDERS.map((provider) => provider.id));
      writeActiveSources();
      syncProviderVisibility();
      syncMarkerVisibility();
      renderSourceList();
      updateSummary();
      refreshAll();
    });

    elements.deactivateAllProviders?.addEventListener("click", () => {
      state.activeSources.clear();
      writeActiveSources();
      syncProviderVisibility();
      syncMarkerVisibility();
      renderSourceList();
      updateSummary();
    });

    elements.regionList?.addEventListener("click", (event) => {
      const button = event.target.closest("[data-region-toggle]");
      if (!button) return;
      event.preventDefault();

      const regionId = button.getAttribute("data-region-toggle");
      if (state.pendingRegions.has(regionId)) state.pendingRegions.delete(regionId);
      else state.pendingRegions.add(regionId);

      renderRegionList();
      syncRegionHighlights();
    });

    elements.regionOk?.addEventListener("click", () => {
      if (!state.pendingRegions.size) {
        syncRegionHighlights();
        return;
      }

      state.visibleRegions = new Set(state.pendingRegions);
      state.selectorComplete = state.visibleRegions.size > 0;
      writeVisibleRegions();
      writeSelectorComplete();
      syncSelectorOverlay();
      syncMarkerVisibility();
      syncRegionHighlights();
      renderSourceList();
      renderRegionList();
      updateSummary();
      fitActiveRegions();
    });

    elements.regionReset?.addEventListener("click", () => {
      state.pendingRegions = new Set(OUTAGE_REGIONS.map((region) => region.id));
      renderRegionList();
      syncRegionHighlights();
    });

    elements.changeRegions?.addEventListener("click", () => {
      state.pendingRegions = new Set(state.visibleRegions);
      state.selectorComplete = false;
      writeSelectorComplete();
      syncSelectorOverlay();
      renderRegionList();
      syncRegionHighlights();
    });

    syncSelectorOverlay();
  }

  function initialiseRegionLayers() {
    OUTAGE_REGIONS.forEach((region) => {
      const rectangle = window.L.rectangle(region.bounds, {
        pane: "outageRegionPane",
        interactive: false,
        color: region.colour,
        weight: 2,
        opacity: 0.42,
        fillColor: region.colour,
        fillOpacity: 0.05,
        dashArray: "5 5"
      });

      rectangle.addTo(state.map);
      state.regionLayers.set(region.id, rectangle);
    });
    renderRegionList();
  }

  function fitUkView() {
    state.map.fitBounds(UK_BOUNDS, { padding: [12, 12] });
    window.requestAnimationFrame(() => {
      const nextZoom = Math.max(state.map.getMinZoom(), state.map.getZoom() - 1);
      state.map.setZoom(nextZoom, { animate: false });
    });
  }

  function readActiveSources() {
    const all = PROVIDERS.map((provider) => provider.id);

    try {
      const stored = window.localStorage.getItem(ACTIVE_SOURCES_KEY);
      if (!stored) return new Set(all);

      const parsed = JSON.parse(stored);
      const valid = new Set(all);
      return new Set(Array.isArray(parsed) ? parsed.filter((id) => valid.has(id)) : all);
    } catch {
      return new Set(all);
    }
  }

  function readVisibleRegions() {
    const all = OUTAGE_REGIONS.map((region) => region.id);

    try {
      const stored = window.localStorage.getItem(VISIBLE_REGIONS_KEY);
      if (!stored) return new Set(all);

      const parsed = JSON.parse(stored);
      const valid = new Set(all);
      return new Set(Array.isArray(parsed) ? parsed.filter((id) => valid.has(id)) : all);
    } catch {
      return new Set(all);
    }
  }

  function readSelectorComplete() {
    try {
      return window.localStorage.getItem(SELECTOR_COMPLETE_KEY) === "true";
    } catch {
      return false;
    }
  }

  function writeActiveSources() {
    try {
      window.localStorage.setItem(
        ACTIVE_SOURCES_KEY,
        JSON.stringify([...state.activeSources])
      );
    } catch {
      // The page remains usable if storage is unavailable.
    }
  }

  function writeVisibleRegions() {
    try {
      window.localStorage.setItem(
        VISIBLE_REGIONS_KEY,
        JSON.stringify([...state.visibleRegions])
      );
    } catch {
      // The region selector remains usable without storage.
    }
  }

  function writeSelectorComplete() {
    try {
      window.localStorage.setItem(SELECTOR_COMPLETE_KEY, state.selectorComplete ? "true" : "false");
    } catch {
      // The selector still works without storage.
    }
  }

  function syncSelectorOverlay() {
    if (!elements.selectorOverlay) return;

    elements.selectorOverlay.hidden = Boolean(state.selectorComplete);
    document.body.classList.toggle("outage-selector-active", !state.selectorComplete);
    window.setTimeout(() => state.map?.invalidateSize({ pan: false }), 120);
  }

  function setSourceActive(sourceId, active) {
    const provider = PROVIDERS.find((item) => item.id === sourceId);
    if (!provider) return;

    if (active) state.activeSources.add(sourceId);
    else state.activeSources.delete(sourceId);

    writeActiveSources();
    syncProviderVisibility();
    syncMarkerVisibility();
    renderSourceList();
    updateSummary();

    const status = state.providerStatus.get(sourceId);
    if (active && !status?.loaded) loadProvider(provider, state.refreshSequence);
  }

  function syncProviderVisibility() {
    PROVIDERS.forEach((provider) => {
      const bundle = state.providerLayers.get(provider.id);
      if (!bundle) return;

      const shouldShow = state.activeSources.has(provider.id);
      const isShown = state.map.hasLayer(bundle.root);

      if (shouldShow && !isShown) bundle.root.addTo(state.map);
      if (!shouldShow && isShown) state.map.removeLayer(bundle.root);
    });
  }

  function syncMarkerVisibility() {
    const categories = {
      current: Boolean(elements.showCurrent?.checked),
      planned: Boolean(elements.showPlanned?.checked),
      restored: Boolean(elements.showRestored?.checked)
    };

    state.providerLayers.forEach((bundle) => {
      bundle.current.clearLayers();
      bundle.planned.clearLayers();
      bundle.restored.clearLayers();
    });

    state.providerRecords.forEach((records, providerId) => {
      const bundle = state.providerLayers.get(providerId);
      if (!bundle) return;

      records.forEach((record) => {
        if (!categories[record.category] || !isRecordInVisibleRegion(record)) return;

        const target = bundle[record.category] || bundle.current;
        if (record.marker) target.addLayer(record.marker);
      });
    });

    syncCategoryGroups(categories);
  }

  function syncCategoryGroups(categories) {
    state.providerLayers.forEach((bundle) => {
      Object.entries(categories).forEach(([category, visible]) => {
        const layer = bundle[category];
        const included = bundle.root.hasLayer(layer);

        if (visible && !included) bundle.root.addLayer(layer);
        if (!visible && included) bundle.root.removeLayer(layer);
      });
    });
  }

  function isRecordInVisibleRegion(record) {
    if (!state.selectorComplete) return false;
    if (state.visibleRegions.size === OUTAGE_REGIONS.length) return true;

    return OUTAGE_REGIONS.some((region) =>
      state.visibleRegions.has(region.id) && pointInBounds(record.lat, record.lon, region.bounds)
    );
  }

  function pointInBounds(lat, lon, bounds) {
    const south = Math.min(bounds[0][0], bounds[1][0]);
    const north = Math.max(bounds[0][0], bounds[1][0]);
    const west = Math.min(bounds[0][1], bounds[1][1]);
    const east = Math.max(bounds[0][1], bounds[1][1]);
    return lat >= south && lat <= north && lon >= west && lon <= east;
  }

  function syncRegionHighlights() {
    OUTAGE_REGIONS.forEach((region) => {
      const layer = state.regionLayers.get(region.id);
      if (!layer) return;

      const active = state.pendingRegions.has(region.id);
      layer.setStyle({
        color: region.colour,
        weight: active ? 3 : 1,
        opacity: active ? 0.86 : 0.18,
        fillColor: region.colour,
        fillOpacity: active ? 0.16 : 0.025,
        dashArray: active ? "" : "5 6"
      });

      if (active) layer.bringToFront();
    });

    if (elements.regionSummary) {
      const count = state.pendingRegions.size;
      elements.regionSummary.textContent = count === OUTAGE_REGIONS.length
        ? "All outage regions selected"
        : `${count} outage region${count === 1 ? "" : "s"} selected`;
    }

    if (elements.regionOk) {
      const disabled = state.pendingRegions.size === 0;
      elements.regionOk.disabled = disabled;
      elements.regionOk.setAttribute("aria-disabled", String(disabled));
    }
  }

  function renderRegionList() {
    if (!elements.regionList) return;

    elements.regionList.innerHTML = OUTAGE_REGIONS.map((region) => {
      const active = state.pendingRegions.has(region.id);
      const records = activeRecords().filter((record) =>
        pointInBounds(record.lat, record.lon, region.bounds)
      );

      return [
        `<button class="outage-region-button${active ? " is-selected" : ""}" style="--outage-region-x:${region.x}%;--outage-region-y:${region.y}%" type="button" data-region-toggle="${escapeAttribute(region.id)}" aria-pressed="${String(active)}">`,
        '<span class="outage-region-swatch" aria-hidden="true"></span>',
        '<span class="outage-region-copy">',
        `<strong>${escapeHtml(region.label)}</strong>`,
        `<small>${records.length} point${records.length === 1 ? "" : "s"}</small>`,
        '</span>',
        '</button>'
      ].join("");
    }).join("");
  }

  function fitActiveRegions() {
    const selected = OUTAGE_REGIONS.filter((region) => state.visibleRegions.has(region.id));
    if (!selected.length) return;

    const bounds = selected.reduce((result, region) => {
      const next = window.L.latLngBounds(region.bounds);
      return result ? result.extend(next) : next;
    }, null);

    if (bounds?.isValid()) state.map.fitBounds(bounds, { padding: [28, 28], maxZoom: 8 });
  }

  async function refreshAll() {
    const sequence = state.refreshSequence + 1;
    state.refreshSequence = sequence;

    if (elements.refresh) {
      elements.refresh.disabled = true;
      elements.refresh.textContent = "Refreshing";
    }

    setHeadline("Loading collected outage datasets", "loading");

    const collectorStatus = await loadCollectorStatus(sequence);
    if (sequence !== state.refreshSequence) return;

    const activeProviders = PROVIDERS.filter((provider) => state.activeSources.has(provider.id));
    await Promise.allSettled(
      activeProviders.map((provider) => loadProvider(
        provider,
        sequence,
        collectorStatus?.providers?.[provider.id]
      ))
    );

    if (sequence !== state.refreshSequence) return;

    if (elements.refresh) {
      elements.refresh.disabled = false;
      elements.refresh.textContent = "Refresh data";
    }

    renderSourceList();
    updateSummary();
  }

  async function loadCollectorStatus(sequence) {
    try {
      const payload = await fetchLocalJson(`${DATA_ROOT}/status.json`, sequence);
      if (sequence !== state.refreshSequence) return null;

      state.collectorGeneratedAt = payload?.generatedAt || null;

      PROVIDERS.forEach((provider) => {
        const collector = payload?.providers?.[provider.id];
        if (!collector) return;

        const previous = state.providerStatus.get(provider.id) || {};
        state.providerStatus.set(provider.id, {
          ...previous,
          ...collector,
          loaded: previous.loaded || false
        });
      });

      return payload;
    } catch (error) {
      state.collectorGeneratedAt = null;
      return null;
    }
  }

  async function loadProvider(provider, sequence, collectorStatus = null) {
    const previousStatus = state.providerStatus.get(provider.id) || {};

    state.providerStatus.set(provider.id, {
      ...previousStatus,
      ...(collectorStatus || {}),
      state: "loading",
      message: "Loading collected GeoJSON"
    });
    renderSourceList();

    try {
      const geojson = await fetchLocalJson(`${DATA_ROOT}/${provider.id}.geojson`, sequence);
      if (sequence !== state.refreshSequence) return;

      if (geojson?.type !== "FeatureCollection" || !Array.isArray(geojson.features)) {
        throw new Error("Invalid GeoJSON file");
      }

      const records = replaceProviderFeatures(provider, geojson.features);
      const baseState = collectorStatus?.state || (records.length ? "live" : "empty");
      const stale = Boolean(geojson.stale || collectorStatus?.stale);

      state.providerStatus.set(provider.id, {
        ...previousStatus,
        ...(collectorStatus || {}),
        state: stale ? "stale" : baseState,
        stale,
        loaded: true,
        uniqueIncidents: records.length,
        message: collectorStatus?.message || (
          stale
            ? `${records.length} last-good incidents`
            : `${records.length} collected incidents`
        )
      });
    } catch (error) {
      if (sequence !== state.refreshSequence) return;

      const existing = state.providerRecords.get(provider.id) || [];
      state.providerStatus.set(provider.id, {
        ...previousStatus,
        ...(collectorStatus || {}),
        state: existing.length ? "stale" : "error",
        stale: existing.length > 0,
        loaded: existing.length > 0,
        uniqueIncidents: existing.length,
        message: existing.length
          ? `${conciseError(error)} · keeping ${existing.length} loaded incidents`
          : conciseError(error)
      });
    } finally {
      renderSourceList();
      renderRegionList();
      updateSummary();
    }
  }

  function replaceProviderFeatures(provider, features) {
    const bundle = state.providerLayers.get(provider.id);
    if (!bundle) return [];

    bundle.current.clearLayers();
    bundle.planned.clearLayers();
    bundle.restored.clearLayers();

    const now = Date.now();
    const records = [];

    features.forEach((feature, index) => {
      featureToRecords(provider, feature, index).forEach((record) => {
        if (!record) return;

        if (!state.firstSeen.has(record.key)) state.firstSeen.set(record.key, now);

        const marker = window.L.marker([record.lat, record.lon], {
          pane: "outageMarkerPane",
          keyboard: true,
          icon: createIncidentIcon(record, now)
        });

        marker.bindPopup(createPopupHtml(record), {
          closeButton: true,
          className: "outage-popup-shell"
        });

        record.marker = marker;
        records.push(record);
      });
    });

    state.providerRecords.set(provider.id, records);
    cleanupFirstSeen();
    syncProviderVisibility();
    syncMarkerVisibility();
    return records;
  }

  function featureToRecord(provider, feature, index) {
    const coordinates = feature?.geometry?.coordinates;
    if (!Array.isArray(coordinates) || coordinates.length < 2) return null;

    const lon = Number(coordinates[0]);
    const lat = Number(coordinates[1]);
    if (!validCoordinate(lat, lon)) return null;

    const properties = feature.properties || {};
    const category = ["current", "planned", "restored"].includes(properties.category)
      ? properties.category
      : "current";

    return {
      key: String(feature.id || `${provider.id}:${category}:${lat}:${lon}:${index}`),
      sourceId: provider.id,
      provider: properties.provider || provider.name,
      reference: properties.reference || null,
      category,
      status: properties.status || category,
      type: properties.type || category,
      area: properties.area || "Published incident location",
      lat,
      lon,
      startedAt: parseTimestamp(properties.startedAt),
      restoreAt: parseTimestamp(properties.restoreAt),
      restoreAtText: properties.restoreAtText || "",
      updatedAt: parseTimestamp(properties.updatedAt),
      officialUrl: safeOfficialUrl(properties.officialUrl, provider.officialUrl),
      locationQuality: properties.locationQuality || "approximate",
      rawRecordCount: Math.max(1, Number(properties.rawRecordCount || 1)),
      coordinateSpreadKm: Math.max(0, Number(properties.coordinateSpreadKm || 0))
    };
  }

  function featureToRecords(provider, feature, index) {
    const primary = featureToRecord(provider, feature, index);
    if (!primary) return [];

    const grouped = Array.isArray(feature?.properties?.groupedLocations)
      ? feature.properties.groupedLocations
      : [];

    if (grouped.length <= 1) return [primary];

    return grouped
      .map((location, childIndex) => childLocationRecord(primary, location, childIndex))
      .filter(Boolean);
  }

  function childLocationRecord(primary, location, index) {
    const lat = Number(location?.lat);
    const lon = Number(location?.lon);
    if (!validCoordinate(lat, lon)) return null;

    return {
      ...primary,
      key: `${primary.key}:location:${index}`,
      reference: location.reference || primary.reference,
      status: location.status || primary.status,
      type: location.type || primary.type,
      area: location.area || primary.area,
      lat,
      lon,
      rawRecordCount: 1,
      coordinateSpreadKm: 0,
      groupedChild: true,
      groupedParentCount: primary.rawRecordCount
    };
  }

  function cleanupFirstSeen() {
    const activeKeys = new Set(
      [...state.providerRecords.values()].flat().map((record) => record.key)
    );

    state.firstSeen.forEach((value, key) => {
      if (!activeKeys.has(key)) state.firstSeen.delete(key);
    });
  }

  function activeRecords() {
    return [...state.activeSources].flatMap(
      (providerId) => state.providerRecords.get(providerId) || []
    );
  }

  function visibleRecords() {
    return activeRecords().filter((record) =>
      isRecordInVisibleRegion(record) && categoryChecked(record.category)
    );
  }

  function categoryChecked(category) {
    if (category === "planned") return Boolean(elements.showPlanned?.checked);
    if (category === "restored") return Boolean(elements.showRestored?.checked);
    return Boolean(elements.showCurrent?.checked);
  }

  function createIncidentIcon(record, now) {
    const colour = categoryColour(record.category);
    const firstSeen = state.firstSeen.get(record.key) || now;
    const durationSeconds = Number(elements.animationDuration?.value || 0);
    const durationMs = durationSeconds * 1000;
    const ageMs = Math.max(0, now - firstSeen);
    const progress = durationMs > 0 ? Math.min(1, ageMs / durationMs) : 1;
    const ringSize = 44 - progress * 28;
    const fadeStart = 0.75;
    const opacity = progress <= fadeStart
      ? 0.82
      : Math.max(0, 0.82 * (1 - ((progress - fadeStart) / (1 - fadeStart))));

    const groupedBadge = record.rawRecordCount > 1
      ? `<span class="outage-marker-count" aria-label="${record.rawRecordCount} provider rows grouped">${record.rawRecordCount}</span>`
      : "";

    return window.L.divIcon({
      className: "outage-marker-shell",
      html: [
        '<span class="outage-marker-ring" style="',
        `--outage-colour:${colour};`,
        `--outage-ring-size:${ringSize.toFixed(2)}px;`,
        `--outage-ring-opacity:${opacity.toFixed(3)};`,
        '" aria-hidden="true"></span>',
        '<span class="outage-marker-core" style="',
        `--outage-colour:${colour};`,
        '" aria-hidden="true"></span>',
        groupedBadge
      ].join(""),
      iconSize: [48, 48],
      iconAnchor: [24, 24]
    });
  }

  function refreshAnimatedMarkers() {
    const now = Date.now();
    state.providerRecords.forEach((records) => {
      records.forEach((record) => {
        if (record.marker) record.marker.setIcon(createIncidentIcon(record, now));
      });
    });
  }

  function categoryColour(category) {
    if (category === "planned") return "#f6b73c";
    if (category === "restored") return "#8193a4";
    return "#f04438";
  }

  function createPopupHtml(record) {
    const grouped = record.rawRecordCount > 1
      ? [
          `<span class="outage-popup-grouped">Grouped from ${record.rawRecordCount} provider rows.</span>`,
          record.coordinateSpreadKm > 0.05
            ? `<span>Published-coordinate spread: ${record.coordinateSpreadKm.toFixed(1)} km.</span>`
            : ""
        ].join("")
      : "";

    return [
      '<div class="outage-popup">',
      `<strong>${escapeHtml(record.provider)}</strong>`,
      `<span class="outage-popup-status">${escapeHtml(humanise(record.type))} · ${escapeHtml(humanise(record.status))}</span>`,
      `<span>${escapeHtml(record.area)}</span>`,
      grouped,
      `<span>Location: ${escapeHtml(humanise(record.locationQuality))}</span>`,
      record.startedAt ? `<span>Started: ${escapeHtml(formatDateTime(record.startedAt))}</span>` : "",
      record.restoreAt ? `<span>Estimated finish: ${escapeHtml(formatDateTime(record.restoreAt))}</span>` : "",
      record.restoreAtText ? `<span>ETR: ${escapeHtml(record.restoreAtText)}</span>` : "",
      record.updatedAt ? `<span>Provider update: ${escapeHtml(formatDateTime(record.updatedAt))}</span>` : "",
      `<span>Reference: ${escapeHtml(record.reference || "Not published")}</span>`,
      `<span>${record.lat.toFixed(4)}, ${record.lon.toFixed(4)}</span>`,
      `<a href="${escapeAttribute(record.officialUrl)}" target="_blank" rel="noopener noreferrer">Open provider map</a>`,
      "</div>"
    ].join("");
  }

  function renderSourceList() {
    if (!elements.sourceList) return;

    elements.sourceList.innerHTML = PROVIDERS.map((provider) => {
      const active = state.activeSources.has(provider.id);
      const sourceState = state.providerStatus.get(provider.id) || {};
      const stateName = active ? sourceState.state || "waiting" : "off";
      const rowClass = sourceStateClass(stateName);
      const stateText = sourceStateLabel(stateName, active);
      const detail = active
        ? sourceState.message || "Waiting for collected data"
        : "Layer deactivated";

      return [
        `<div class="outage-source-row is-${escapeAttribute(rowClass)}">`,
        `<button class="outage-source-toggle" type="button" data-source-toggle="${escapeAttribute(provider.id)}" aria-pressed="${String(active)}">`,
        '<span class="outage-source-dot" aria-hidden="true"></span>',
        '<span class="outage-source-copy">',
        `<strong>${escapeHtml(provider.name)}</strong>`,
        `<small>${escapeHtml(detail)}</small>`,
        "</span>",
        `<span class="outage-source-switch-state">${escapeHtml(stateText)}</span>`,
        "</button>",
        `<a class="outage-source-link" href="${escapeAttribute(provider.officialUrl)}" target="_blank" rel="noopener noreferrer">Map</a>`,
        "</div>"
      ].join("");
    }).join("");
  }

  function sourceStateLabel(stateName, active) {
    if (!active) return "OFF";
    if (stateName === "live") return "LIVE";
    if (stateName === "stale") return "STALE";
    if (stateName === "unavailable") return "UNAVAILABLE";
    if (stateName === "authentication required") return "AUTH";
    if (stateName === "source failure") return "SOURCE";
    if (stateName === "partial") return "PARTIAL";
    if (stateName === "empty") return "EMPTY";
    if (stateName === "error") return "ERROR";
    if (stateName === "loading") return "LOADING";
    return "WAITING";
  }

  function sourceStateClass(stateName) {
    if (["stale", "partial"].includes(stateName)) return "warning";
    if (["unavailable", "authentication required", "source failure", "error"].includes(stateName)) {
      return "error";
    }
    return String(stateName || "waiting").replace(/\s+/g, "-");
  }

  function updateSummary() {
    const records = visibleRecords();
    const loadedRecords = activeRecords();
    const current = records.filter((item) => item.category === "current").length;
    const planned = records.filter((item) => item.category === "planned").length;
    const restored = records.filter((item) => item.category === "restored").length;
    const activeStatuses = [...state.activeSources]
      .map((id) => state.providerStatus.get(id))
      .filter(Boolean);

    const loaded = activeStatuses.filter((item) => item.loaded).length;
    const errors = activeStatuses.filter((item) =>
      ["error", "unavailable", "authentication required", "source failure"].includes(item.state)
    ).length;
    const stale = activeStatuses.filter((item) => item.state === "stale" || item.stale).length;
    const rawRows = activeStatuses.reduce((sum, item) => sum + Number(item.rawRows || 0), 0);
    const groupedRows = activeStatuses.reduce((sum, item) => sum + Number(item.groupedRows || 0), 0);

    elements.currentCount.textContent = String(current);
    elements.plannedCount.textContent = String(planned);
    elements.restoredCount.textContent = String(restored);
    elements.providerCount.textContent = `${loaded}/${state.activeSources.size}`;
    elements.rawRowCount.textContent = String(rawRows);
    elements.uniqueIncidentCount.textContent = String(records.length);
    elements.groupedRowCount.textContent = String(groupedRows);

    const generated = state.collectorGeneratedAt
      ? ` · updated ${formatRelativeTime(state.collectorGeneratedAt)}`
      : "";

    elements.sourceSummary.textContent =
      `${state.activeSources.size}/${PROVIDERS.length} providers · ${records.length}/${loadedRecords.length} points shown${generated}`;

    if (state.activeSources.size === 0) {
      setHeadline("All outage providers deactivated", "error");
      elements.statusText.textContent = "All provider LayerGroups are hidden. Region selection is preserved.";
      return;
    }

    if (loaded === state.activeSources.size && errors === 0 && stale === 0) {
      setHeadline(`${current} current · ${planned} planned`, "live");
    } else if (loaded > 0) {
      setHeadline(
        `${current} current · ${planned} planned · ${errors + stale} dataset issue${errors + stale === 1 ? "" : "s"}`,
        "partial"
      );
    } else {
      setHeadline("Collected outage data unavailable", "error");
    }

    elements.statusText.textContent = records.length
      ? `Showing ${records.length} selected outage points from ${loadedRecords.length} loaded incidents and ${rawRows} collected provider rows. ${groupedRows} repeated rows were grouped.`
      : "No outage points match the selected regions and filters. Open Regions to show more points, or Outage providers to inspect dataset status.";
  }

  function setHeadline(message, mode) {
    elements.headlineStatus.textContent = message;
    elements.liveBadge.className = "weather-pill outage-live-pill";

    if (mode === "live") {
      elements.liveBadge.textContent = "LIVE";
      elements.liveBadge.classList.add("is-live");
    } else if (mode === "partial") {
      elements.liveBadge.textContent = "PARTIAL";
      elements.liveBadge.classList.add("is-partial");
    } else if (mode === "error") {
      elements.liveBadge.textContent = "ERROR";
      elements.liveBadge.classList.add("is-error");
    } else {
      elements.liveBadge.textContent = "LOADING";
    }
  }

  async function fetchLocalJson(path, sequence) {
    const separator = path.includes("?") ? "&" : "?";
    const response = await fetch(`${path}${separator}v=${sequence}-${Date.now()}`, {
      cache: "no-store",
      headers: { Accept: "application/json" }
    });

    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return response.json();
  }

  function parseTimestamp(value) {
    if (!value) return null;
    const parsed = Date.parse(value);
    return Number.isFinite(parsed) ? parsed : null;
  }

  function validCoordinate(lat, lon) {
    return Number.isFinite(lat) && Number.isFinite(lon) &&
      lat >= 48 && lat <= 62.5 && lon >= -12.5 && lon <= 4;
  }

  function safeOfficialUrl(value, fallback) {
    try {
      const url = new URL(value || fallback, window.location.href);
      return ["http:", "https:"].includes(url.protocol) ? url.href : fallback;
    } catch {
      return fallback;
    }
  }

  function formatDateTime(timestamp) {
    return new Intl.DateTimeFormat("en-GB", {
      day: "2-digit",
      month: "short",
      hour: "2-digit",
      minute: "2-digit",
      timeZone: "Europe/London",
      timeZoneName: "short"
    }).format(new Date(timestamp));
  }

  function formatRelativeTime(value) {
    const timestamp = Date.parse(value);
    if (!Number.isFinite(timestamp)) return "unknown";

    const minutes = Math.max(0, Math.round((Date.now() - timestamp) / 60_000));
    if (minutes < 2) return "just now";
    if (minutes < 60) return `${minutes} min ago`;

    const hours = Math.round(minutes / 60);
    return `${hours} h ago`;
  }

  function humanise(value) {
    return String(value || "Published")
      .replaceAll("_", " ")
      .replaceAll("-", " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  function conciseError(error) {
    return String(error?.message || "Unavailable").slice(0, 110);
  }

  function escapeHtml(value) {
    return String(value ?? "")
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;")
      .replaceAll("'", "&#039;");
  }

  function escapeAttribute(value) {
    return escapeHtml(value);
  }

  window.FieldOpsOutages = {
    version: VERSION,
    refresh: refreshAll,
    diagnostics: () => ({
      generatedAt: state.collectorGeneratedAt,
      providers: Object.fromEntries(state.providerStatus.entries()),
      counts: Object.fromEntries(
        [...state.providerRecords.entries()].map(([id, records]) => [id, records.length])
      )
    })
  };

  document.addEventListener("DOMContentLoaded", init, { once: true });
})();
